#!/usr/bin/env node
// Freeze the SQLite schema the Node app creates into
// tests/contract/fixtures/schema.sql.
//
// The contract seed is built from this file with plain better-sqlite3 — no
// app code — so the same seed can be fed to the Go backend (and still
// exists once src/core/db.js is gone). tests/contract/inventory.contract.test.js
// fails when the frozen file no longer matches what db.js creates; rerun
// this script (and re-record the snapshots) after a schema change.
//
// Usage: node scripts/contract-schema.mjs [--check]

import { execFileSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(REPO, 'tests', 'contract', 'fixtures', 'schema.sql');

export function dumpNodeSchema() {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tgdl-schema-'));
    try {
        // Child process: db.js is a singleton bound to TGDL_DATA_DIR at import.
        const code = `
            const db = await import(${JSON.stringify(pathToFileURL(path.join(REPO, 'src/core/db.js')).href)});
            const d = db.getDb();
            const rows = d.prepare("SELECT type, name, tbl_name, sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY rowid").all();
            process.stdout.write(JSON.stringify(rows));
            d.close();
        `;
        const out = execFileSync(process.execPath, ['--input-type=module', '-e', code], {
            env: { ...process.env, TGDL_DATA_DIR: dir },
            encoding: 'utf8',
            stdio: ['ignore', 'pipe', 'ignore'],
        });
        const rows = JSON.parse(out);
        // FTS5 shadow tables are created by the virtual table itself.
        const fts = new Set(rows.filter((r) => /VIRTUAL TABLE/i.test(r.sql)).map((r) => r.name));
        const keep = rows.filter(
            (r) =>
                !r.name.startsWith('sqlite_') &&
                ![...fts].some(
                    (v) => r.name !== v && r.name.startsWith(`${v}_`) && r.type === 'table',
                ),
        );
        return (
            '-- Generated by scripts/contract-schema.mjs from src/core/db.js. Do not edit.\n' +
            keep.map((r) => `${r.sql.replace(/\r\n/g, '\n').trim()};`).join('\n\n') +
            '\n'
        );
    } finally {
        fs.rmSync(dir, { recursive: true, force: true });
    }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
    const sql = dumpNodeSchema();
    if (process.argv.includes('--check')) {
        const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : '';
        if (cur !== sql) {
            console.error(
                'tests/contract/fixtures/schema.sql is stale — run: node scripts/contract-schema.mjs',
            );
            process.exit(1);
        }
        console.log('schema.sql up to date');
    } else {
        fs.mkdirSync(path.dirname(OUT), { recursive: true });
        fs.writeFileSync(OUT, sql);
        console.log(`wrote ${path.relative(REPO, OUT)}`);
    }
}
