-- Generated by scripts/contract-schema.mjs from src/core/db.js. Do not edit.
CREATE TABLE downloads (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            group_id TEXT NOT NULL,
            group_name TEXT,
            message_id INTEGER NOT NULL,
            file_name TEXT,
            file_size INTEGER,
            file_type TEXT, -- photo, video, document
            file_path TEXT,
            status TEXT DEFAULT 'completed',
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP, ttl_seconds INTEGER, file_hash TEXT, pinned INTEGER DEFAULT 0, pending_until INTEGER, rescued_at INTEGER, nsfw_score REAL, nsfw_checked_at INTEGER, nsfw_whitelist INTEGER DEFAULT 0, ai_indexed_at INTEGER, owner_peer_id TEXT,
            UNIQUE(group_id, message_id)
        );

CREATE INDEX idx_group_id ON downloads(group_id);

CREATE INDEX idx_created_at ON downloads(created_at);

CREATE INDEX idx_filename_size ON downloads(group_id, file_name, file_size);

CREATE INDEX idx_pending_until ON downloads(pending_until) WHERE pending_until IS NOT NULL;

CREATE INDEX idx_group_message ON downloads(group_id, message_id);

CREATE INDEX idx_nsfw_unscanned ON downloads(file_type, nsfw_checked_at) WHERE nsfw_checked_at IS NULL;

CREATE INDEX idx_nsfw_review ON downloads(nsfw_score, nsfw_whitelist) WHERE nsfw_score IS NOT NULL;

CREATE INDEX idx_nsfw_tier ON downloads(file_type, nsfw_whitelist, nsfw_score) WHERE nsfw_score IS NOT NULL;

CREATE INDEX idx_file_hash ON downloads(file_hash) WHERE file_hash IS NOT NULL;

CREATE INDEX idx_unhashed ON downloads(id DESC) WHERE file_hash IS NULL AND file_path IS NOT NULL;

CREATE INDEX idx_gallery_group_date ON downloads(group_id, created_at DESC, id DESC);

CREATE INDEX idx_gallery_group_type_date ON downloads(group_id, file_type, created_at DESC, id DESC);

CREATE INDEX idx_gallery_type_date ON downloads(file_type, created_at DESC, id DESC);

CREATE INDEX idx_gallery_pinned_date ON downloads(pinned DESC, created_at DESC, id DESC);

CREATE INDEX idx_file_path ON downloads(file_path);

CREATE INDEX idx_group_name_size ON downloads(group_id, group_name, file_size);

CREATE INDEX idx_gallery_type_pinned_date ON downloads(file_type, pinned DESC, created_at DESC, id DESC);

CREATE INDEX idx_gallery_group_pinned_date ON downloads(group_id, pinned DESC, created_at DESC, id DESC);

CREATE INDEX idx_video_filepath ON downloads(file_type, id DESC) WHERE file_type = 'video' AND file_path IS NOT NULL;

CREATE VIRTUAL TABLE downloads_fts USING fts5(
                file_name, group_name,
                content='downloads',
                content_rowid='id'
            );

CREATE TRIGGER downloads_fts_insert AFTER INSERT ON downloads BEGIN
                INSERT INTO downloads_fts(rowid, file_name, group_name)
                VALUES (new.id, COALESCE(new.file_name,''), COALESCE(new.group_name,''));
            END;

CREATE TRIGGER downloads_fts_delete AFTER DELETE ON downloads BEGIN
                INSERT INTO downloads_fts(downloads_fts, rowid, file_name, group_name)
                VALUES ('delete', old.id, COALESCE(old.file_name,''), COALESCE(old.group_name,''));
            END;

CREATE TRIGGER downloads_fts_update AFTER UPDATE OF file_name, group_name ON downloads BEGIN
                INSERT INTO downloads_fts(downloads_fts, rowid, file_name, group_name)
                VALUES ('delete', old.id, COALESCE(old.file_name,''), COALESCE(old.group_name,''));
                INSERT INTO downloads_fts(rowid, file_name, group_name)
                VALUES (new.id, COALESCE(new.file_name,''), COALESCE(new.group_name,''));
            END;

CREATE TABLE nsfw_hash_blocklist (
                file_hash  TEXT    PRIMARY KEY,
                file_name  TEXT,
                deleted_at INTEGER NOT NULL,
                source     TEXT    DEFAULT 'manual'
            );

CREATE TABLE image_embeddings (
            download_id INTEGER PRIMARY KEY,
            embedding   BLOB    NOT NULL,
            model       TEXT    NOT NULL,
            indexed_at  INTEGER NOT NULL,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE TABLE image_tags (
            download_id INTEGER NOT NULL,
            tag         TEXT    NOT NULL,
            score       REAL    NOT NULL,
            PRIMARY KEY (download_id, tag),
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE INDEX idx_tags_tag_score ON image_tags(tag, score DESC);

CREATE TABLE people (
            id                 INTEGER PRIMARY KEY AUTOINCREMENT,
            label              TEXT,
            embedding_centroid BLOB    NOT NULL,
            face_count         INTEGER NOT NULL DEFAULT 0,
            created_at         INTEGER NOT NULL,
            updated_at         INTEGER NOT NULL
        , gender TEXT);

CREATE TABLE faces (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            download_id INTEGER NOT NULL,
            x           REAL    NOT NULL,
            y           REAL    NOT NULL,
            w           REAL    NOT NULL,
            h           REAL    NOT NULL,
            embedding   BLOB    NOT NULL,
            person_id   INTEGER, quality_score REAL, exif_oriented INTEGER, frame_time_sec REAL, gender TEXT,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE,
            FOREIGN KEY (person_id)   REFERENCES people(id)    ON DELETE SET NULL
        );

CREATE INDEX idx_faces_download ON faces(download_id);

CREATE INDEX idx_faces_person   ON faces(person_id);

CREATE TRIGGER trg_purge_orphan_people
        AFTER DELETE ON faces
        WHEN OLD.person_id IS NOT NULL
        BEGIN
            DELETE FROM people
             WHERE id = OLD.person_id
               AND NOT EXISTS (SELECT 1 FROM faces WHERE person_id = OLD.person_id);
        END;

CREATE INDEX idx_ai_unindexed ON downloads(file_type, ai_indexed_at) WHERE ai_indexed_at IS NULL;

CREATE TABLE peer_face_centroids (
            peer_id          TEXT    NOT NULL,
            remote_person_id INTEGER NOT NULL,
            centroid         BLOB    NOT NULL,
            label            TEXT,
            face_count       INTEGER NOT NULL DEFAULT 0,
            updated_at       INTEGER NOT NULL,
            PRIMARY KEY (peer_id, remote_person_id)
        );

CREATE INDEX idx_peer_face_centroids_label
            ON peer_face_centroids(label) WHERE label IS NOT NULL;

CREATE TABLE seekbar_sprites (
            download_id   INTEGER PRIMARY KEY,
            sprite_path   TEXT NOT NULL,
            meta_path     TEXT NOT NULL,
            duration_sec  REAL,
            frames        INTEGER,
            cols          INTEGER,
            rows          INTEGER,
            tile_w        INTEGER,
            tile_h        INTEGER,
            interval_sec  REAL,
            format        TEXT,
            bytes         INTEGER,
            source_size   INTEGER,
            source_mtime  INTEGER,
            generated_at  INTEGER NOT NULL,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE INDEX idx_seekbar_generated_at ON seekbar_sprites(generated_at);

CREATE TABLE video_fingerprints (
            download_id     INTEGER PRIMARY KEY,
            duration_sec    REAL,
            aggregate_hash  TEXT,
            frame_count     INTEGER NOT NULL DEFAULT 0,
            algo            TEXT    NOT NULL DEFAULT 'pdq-scene-v1',
            indexed_at      INTEGER NOT NULL,
            file_hash       TEXT,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE INDEX video_fingerprints_file_hash_idx
            ON video_fingerprints(file_hash);

CREATE INDEX video_fingerprints_aggregate_hash_idx
            ON video_fingerprints(aggregate_hash);

CREATE TABLE video_frame_hashes (
            download_id INTEGER NOT NULL,
            t_sec       REAL    NOT NULL,
            phash       TEXT    NOT NULL,
            PRIMARY KEY (download_id, t_sec),
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE INDEX video_frame_hashes_download_id_idx
            ON video_frame_hashes(download_id);

CREATE TABLE similar_groups (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            kind        TEXT    NOT NULL CHECK (kind IN ('similar', 'partial', 'partial_review')),
            confidence  REAL,
            offset_sec  REAL,
            created_at  INTEGER NOT NULL
        );

CREATE TABLE similar_group_members (
            group_id    INTEGER NOT NULL,
            download_id INTEGER NOT NULL,
            role        TEXT    NOT NULL CHECK (role IN ('keep', 'remove', 'review')),
            reason      TEXT,
            PRIMARY KEY (group_id, download_id),
            FOREIGN KEY (group_id) REFERENCES similar_groups(id) ON DELETE CASCADE,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE INDEX similar_group_members_download_id_idx
            ON similar_group_members(download_id);

CREATE TABLE similar_ignores (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            a_id        INTEGER NOT NULL,
            b_id        INTEGER NOT NULL,
            kind        TEXT    NOT NULL CHECK (kind IN ('similar', 'partial', 'partial_review')),
            ignored_at  INTEGER NOT NULL,
            note        TEXT,
            UNIQUE (kind, a_id, b_id),
            CHECK (a_id < b_id),
            FOREIGN KEY (a_id) REFERENCES downloads(id) ON DELETE CASCADE,
            FOREIGN KEY (b_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE TABLE similar_partial_scans (
            download_id INTEGER PRIMARY KEY,
            frame_count INTEGER NOT NULL,
            scanned_at  INTEGER NOT NULL,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE TABLE similar_video_scans (
            download_id INTEGER PRIMARY KEY,
            file_hash   TEXT,
            frame_count INTEGER NOT NULL,
            algo        TEXT    NOT NULL,
            config_key  TEXT    NOT NULL,
            scanned_at  INTEGER NOT NULL,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE TABLE queue (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            group_id TEXT NOT NULL,
            message_id INTEGER NOT NULL,
            meta TEXT, -- JSON payload
            priority INTEGER DEFAULT 0,
            status TEXT DEFAULT 'pending', -- pending, processing, failed
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE share_links (
            id               INTEGER PRIMARY KEY AUTOINCREMENT,
            download_id      INTEGER NOT NULL,
            created_at       INTEGER NOT NULL,
            expires_at       INTEGER NOT NULL,
            revoked_at       INTEGER,
            label            TEXT,
            last_accessed_at INTEGER,
            access_count     INTEGER NOT NULL DEFAULT 0,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE INDEX idx_share_links_download ON share_links(download_id);

CREATE INDEX idx_share_links_expiry ON share_links(expires_at);

CREATE TABLE backup_destinations (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            name            TEXT    NOT NULL,
            provider        TEXT    NOT NULL,
            config_blob     BLOB    NOT NULL,
            enabled         INTEGER NOT NULL DEFAULT 1,
            encryption      INTEGER NOT NULL DEFAULT 0,
            encryption_salt BLOB,
            mode            TEXT    NOT NULL DEFAULT 'mirror',
            cron            TEXT,
            retain_count    INTEGER DEFAULT 7,
            last_success_at INTEGER,
            last_failure_at INTEGER,
            last_error      TEXT,
            total_bytes     INTEGER NOT NULL DEFAULT 0,
            total_files     INTEGER NOT NULL DEFAULT 0,
            throttle_bps    INTEGER,
            created_at      INTEGER NOT NULL
        );

CREATE TABLE backup_jobs (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            destination_id  INTEGER NOT NULL,
            download_id     INTEGER,
            snapshot_path   TEXT,
            status          TEXT    NOT NULL DEFAULT 'pending',
            attempts        INTEGER NOT NULL DEFAULT 0,
            max_attempts    INTEGER NOT NULL DEFAULT 5,
            next_retry_at   INTEGER,
            started_at      INTEGER,
            finished_at     INTEGER,
            bytes_uploaded  INTEGER NOT NULL DEFAULT 0,
            error           TEXT,
            remote_path     TEXT,
            FOREIGN KEY (destination_id) REFERENCES backup_destinations(id) ON DELETE CASCADE,
            FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
        );

CREATE INDEX idx_backup_jobs_pending ON backup_jobs(destination_id, status, next_retry_at);

CREATE INDEX idx_backup_jobs_download ON backup_jobs(download_id);

CREATE TABLE kv (
            key        TEXT    PRIMARY KEY,
            value      TEXT    NOT NULL,
            updated_at INTEGER NOT NULL
        );

CREATE TABLE chat_access (
                chat_id       TEXT    PRIMARY KEY,
                state         TEXT    NOT NULL,
                code          TEXT,
                detail        TEXT,
                migrated_to   TEXT,
                first_seen_at INTEGER,
                checked_at    INTEGER NOT NULL,
                next_check_at INTEGER,
                checks        INTEGER NOT NULL DEFAULT 0,
                accounts      TEXT,
                updated_at    INTEGER NOT NULL
            );

CREATE TABLE web_sessions (
            token      TEXT    PRIMARY KEY,
            role       TEXT    NOT NULL CHECK(role IN ('admin','guest')),
            issued_at  INTEGER NOT NULL,
            expires_at INTEGER NOT NULL,
            last_seen  INTEGER NOT NULL
        );

CREATE INDEX idx_web_sessions_expires ON web_sessions(expires_at);

CREATE INDEX idx_web_sessions_role    ON web_sessions(role);

CREATE TABLE update_history (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            from_version TEXT,
            to_version   TEXT,
            started_at   INTEGER NOT NULL,
            finished_at  INTEGER,
            status       TEXT    NOT NULL DEFAULT 'pending',
            error_code   TEXT,
            error_msg    TEXT,
            backup_path  TEXT,
            backup_bytes INTEGER
        , from_instance_id TEXT);

CREATE INDEX idx_update_history_status ON update_history(status, started_at);

CREATE TABLE peers (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            peer_id      TEXT    NOT NULL UNIQUE,
            name         TEXT    NOT NULL,
            url          TEXT    NOT NULL,
            status       TEXT    NOT NULL DEFAULT 'offline',
            stream_mode  TEXT    NOT NULL DEFAULT 'proxy',
            last_seen_at INTEGER,
            paired_at    INTEGER NOT NULL,
            fingerprint  TEXT    NOT NULL,
            version      TEXT,
            notes        TEXT
        , shared_secret BLOB, role TEXT NOT NULL DEFAULT 'admin', ws_last_seen INTEGER);

CREATE INDEX idx_peers_status ON peers(status);

CREATE TABLE peer_downloads (
            peer_id     TEXT    NOT NULL,
            remote_id   INTEGER NOT NULL,
            file_path   TEXT    NOT NULL,
            file_name   TEXT,
            file_size   INTEGER,
            file_type   TEXT,
            file_hash   TEXT,
            group_id    TEXT,
            group_name  TEXT,
            message_id  INTEGER,
            created_at  INTEGER,
            status      TEXT,
            nsfw_score  REAL,
            cached_at   INTEGER NOT NULL,
            PRIMARY KEY (peer_id, remote_id)
        );

CREATE INDEX idx_peer_downloads_hash    ON peer_downloads(file_hash, file_size);

CREATE INDEX idx_peer_downloads_group   ON peer_downloads(group_id);

CREATE INDEX idx_peer_downloads_created ON peer_downloads(created_at DESC);

CREATE TABLE peer_groups (
            peer_id    TEXT    PRIMARY KEY,
            payload    TEXT    NOT NULL,
            cached_at  INTEGER NOT NULL
        );

CREATE TABLE peer_accounts (
            peer_id    TEXT    PRIMARY KEY,
            payload    TEXT    NOT NULL,
            cached_at  INTEGER NOT NULL
        );

CREATE TABLE peer_history (
            peer_id    TEXT    PRIMARY KEY,
            payload    TEXT    NOT NULL,
            cached_at  INTEGER NOT NULL
        );

CREATE TABLE cluster_audit (
            id      INTEGER PRIMARY KEY AUTOINCREMENT,
            ts      INTEGER NOT NULL,
            peer_id TEXT,
            kind    TEXT    NOT NULL,
            detail  TEXT,
            ok      INTEGER NOT NULL DEFAULT 1
        );

CREATE INDEX idx_cluster_audit_ts ON cluster_audit(ts DESC);

CREATE TABLE peer_failover_log (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            group_id     TEXT    NOT NULL,
            from_peer_id TEXT    NOT NULL,
            to_peer_id   TEXT    NOT NULL,
            reason       TEXT,
            ts           INTEGER NOT NULL
        );

CREATE INDEX idx_failover_ts ON peer_failover_log(ts DESC);

CREATE TABLE peer_delete_jobs (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            peer_id      TEXT    NOT NULL,
            remote_id    INTEGER NOT NULL,
            reason       TEXT,
            status       TEXT    NOT NULL DEFAULT 'pending',
            attempts     INTEGER NOT NULL DEFAULT 0,
            created_at   INTEGER NOT NULL,
            finished_at  INTEGER
        );

CREATE INDEX idx_pdj_pending ON peer_delete_jobs(status, peer_id);

CREATE TABLE peer_discoveries (
            peer_id    TEXT    PRIMARY KEY,
            url        TEXT    NOT NULL,
            name       TEXT,
            version    TEXT,
            source     TEXT    NOT NULL DEFAULT 'broadcast',
            seen_at    INTEGER NOT NULL
        );

CREATE TABLE cluster_egress_log (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            peer_id     TEXT,
            bytes       INTEGER NOT NULL,
            served_at   INTEGER NOT NULL,
            from_cache  INTEGER NOT NULL DEFAULT 0
        );

CREATE INDEX idx_cluster_egress_time ON cluster_egress_log(served_at);
